# Project-wide Gradle settings.
# IDE (e.g. Android Studio) users:
# Gradle settings configured through the IDE *will override*
# any settings specified in this file.
# For more details on how to configure your build environment visit
# http://www.gradle.org/docs/current/userguide/build_environment.html
# Specifies the JVM arguments used for the daemon process.
# The setting is particularly useful for tweaking memory settings.
# When configured, Gradle will run in incubating parallel mode.
# This option should only be used with decoupled projects. More details, visit
# http://www.gradle.org/docs/current/userguide/multi_project_builds.html#sec:decoupled_projects
# org.gradle.parallel=true
# AndroidX package structure to make it clearer which packages are bundled with the
# Android operating system, and which are packaged with your app"s APK
# https://developer.android.com/topic/libraries/support-library/androidx-rn
android.useAndroidX=true
# Automatically convert third-party libraries to use AndroidX
android.enableJetifier=true
# Kotlin code style for this project: "official" or "obsolete":
kotlin.code.style=official
android.suppressUnsupportedCompileSdk=34
# Optional custom signing config for app/build.gradle
# Fill these in local-only if you want the app to build with your real keystore.
# Example:
AI_GIRL_STORE_FILE=app/ai-chat-key-upload.jks
AI_GIRL_STORE_PASSWORD=com.pegas.yuki.virtual.chat
AI_GIRL_KEY_ALIAS=key0
AI_GIRL_KEY_PASSWORD=com.pegas.yuki.virtual.chat
REVENUECAT_ANDROID_PUBLIC_API_KEY=goog_WAACxFyyfIkWTkxHbKMxofHibDW

